spring:
  application:
    name: simple-communicator-server
logging:
  level:
    ru.dnechoroshev.simplecommunicator.model.Participant: DEBUG

general:
  debug:
    enable-auto-response: true
    auto-response-callee: DummyAbonent